// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAST80UE0ulIUyFO2pXgrT-7Dcm5eyzMiU',
    appId: '1:125074343173:web:afa84b8b564c900d07236c',
    messagingSenderId: '125074343173',
    projectId: 'module2firebase',
    authDomain: 'module2firebase.firebaseapp.com',
    storageBucket: 'module2firebase.firebasestorage.app',
    measurementId: 'G-V7FJ88FM16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fKCAI76vIFUHcXWryF7DJqXNC0_rN5I',
    appId: '1:125074343173:android:a8c7f616a668ff9707236c',
    messagingSenderId: '125074343173',
    projectId: 'module2firebase',
    storageBucket: 'module2firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVpAKQPMl7VzjJcp7YWLTrEgkcQRfCR8',
    appId: '1:125074343173:ios:6036b0f660be837507236c',
    messagingSenderId: '125074343173',
    projectId: 'module2firebase',
    storageBucket: 'module2firebase.firebasestorage.app',
    iosBundleId: 'com.example.module2firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVpAKQPMl7VzjJcp7YWLTrEgkcQRfCR8',
    appId: '1:125074343173:ios:6036b0f660be837507236c',
    messagingSenderId: '125074343173',
    projectId: 'module2firebase',
    storageBucket: 'module2firebase.firebasestorage.app',
    iosBundleId: 'com.example.module2firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAST80UE0ulIUyFO2pXgrT-7Dcm5eyzMiU',
    appId: '1:125074343173:web:a8fb92c67b01053207236c',
    messagingSenderId: '125074343173',
    projectId: 'module2firebase',
    authDomain: 'module2firebase.firebaseapp.com',
    storageBucket: 'module2firebase.firebasestorage.app',
    measurementId: 'G-D81TX2B1EX',
  );
}
